---
id: Alarm
name: Alarm
full: Alarm library
description: |
  A library to deal with reminders, alarms and notifications through a standardized API. The following notification methods are currently available: standard Horde notifications, desktop notifications, emails.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Alarm
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 3.0.0alpha2
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/date: ^3
      horde/exception: ^3
      horde/translation: ^3
  optional:
    composer:
      horde/db: ^3
      horde/log: ^3
      horde/mail: ^3
      horde/mime: ^3
      horde/notification: ^3
      horde/perms: ^3
      horde/prefs: ^3
      horde/test: ^3
