---
id: Alarm
name: Alarm
full: Alarm library
description: |
  A library to deal with reminders, alarms and notifications through a standardized API. The following notification methods are currently available: standard Horde notifications, desktop notifications, emails.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Alarm
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 2.2.11
  api: 1.2.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Date: ^2
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Translation: ^2.2
  optional:
    pear:
      pear.horde.org/Horde_Db: ^2.2
      pear.horde.org/Horde_Log: ^2
      pear.horde.org/Horde_Mail: ^2
      pear.horde.org/Horde_Mime: ^2
      pear.horde.org/Horde_Notification: ^2
      pear.horde.org/Horde_Perms: ^2
      pear.horde.org/Horde_Prefs: ^2
      pear.horde.org/Horde_Test: ^2.1
